<a href="https://colab.research.google.com/github/matsunori39/Law-of-Awesome-Data-Scientist/blob/main/Law_of_Awesome_Data_Scientist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ipython-sql -q

In [2]:
# ipython-sqlの読み込み
%load_ext sql

# SQLiteへの接続
%sql sqlite:///tmp.sqlite3

'Connected: @tmp.sqlite3'

In [3]:
!git clone https://github.com/ghmagazine/awesomebook

Cloning into 'awesomebook'...
remote: Enumerating objects: 338, done.
remote: Total 338 (delta 0), reused 0 (delta 0), pack-reused 338
Receiving objects: 100% (338/338), 220.77 KiB | 16.98 MiB/s, done.
Resolving deltas: 100% (69/69), done.

In [4]:
import pandas as pd

In [5]:
reserve_tb = pd.read_csv("/content/awesomebook/data/reserve.csv", encoding="UTF-8")

In [6]:
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100

In [7]:
reserve_tb[["reserve_id", "hotel_id", "customer_id", "reserve_datetime", "checkin_date", "checkin_time", "checkout_date"]]

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23
...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09

In [8]:
reserve_tb.drop(['people_num', 'total_price'], axis=1)

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23
...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09

In [9]:
reserve_tb

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100
...,...,...,...,...,...,...,...,...,...
4025,r4026,h_129,c_999,2017-06-27 23:00:02,2017-07-10,09:30:00,2017-07-11,2,16000
4026,r4027,h_97,c_999,2017-09-29 05:24:57,2017-10-09,10:30:00,2017-10-10,2,41800
4027,r4028,h_27,c_999,2018-03-14 05:01:45,2018-04-02,11:30:00,2018-04-04,2,74800
4028,r4029,h_48,c_1000,2016-04-16 15:20:17,2016-05-10,09:30:00,2016-05-13,4,540000
4029,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100

In [10]:
import sqlite3

with sqlite3.connect("tmp.sqlite3") as conn:
    reserve_tb.to_sql('reserve_tb', con=conn)

In [11]:
%%sql
SELECT
  reserve_id AS rsv_time,
  hotel_id, customer_id, reserve_datetime,
  checkin_date, checkin_time, checkout_date
FROM reserve_tb

 * sqlite:///tmp.sqlite3
Done.

[('r1', 'h_75', 'c_1', '2016-03-06 13:09:42', '2016-03-26', '10:00:00', '2016-03-29'),
 ('r2', 'h_219', 'c_1', '2016-07-16 23:39:55', '2016-07-20', '11:30:00', '2016-07-21'),
 ('r3', 'h_179', 'c_1', '2016-09-24 10:03:17', '2016-10-19', '09:00:00', '2016-10-22'),
 ('r4', 'h_214', 'c_1', '2017-03-08 03:20:10', '2017-03-29', '11:00:00', '2017-03-30'),
 ('r5', 'h_16', 'c_1', '2017-09-05 19:50:37', '2017-09-22', '10:30:00', '2017-09-23'),
 ('r6', 'h_241', 'c_1', '2017-11-27 18:47:05', '2017-12-04', '12:00:00', '2017-12-06'),
 ('r7', 'h_256', 'c_1', '2017-12-29 10:38:36', '2018-01-25', '10:30:00', '2018-01-28'),
 ('r8', 'h_241', 'c_1', '2018-05-26 08:42:51', '2018-06-08', '10:00:00', '2018-06-09'),
 ('r9', 'h_217', 'c_2', '2016-03-05 13:31:06', '2016-03-25', '09:30:00', '2016-03-27'),
 ('r10', 'h_240', 'c_2', '2016-06-25 09:12:22', '2016-07-14', '11:00:00', '2016-07-17'),
 ('r11', 'h_183', 'c_2', '2016-11-19 12:49:10', '2016-12-08', '11:00:00', '2016-12-11'),
 ('r12', 'h_268', 'c_2', '2017-05-24 10:06:21', '2017-06-20', '09:00:00', '2017-06-21'),
 ('r13', 'h_223', 'c_2', '2017-10-19 03:03:30', '2017-10-21', '09:30:00', '2017-10-23'),
 ('r14', 'h_133', 'c_2', '2018-02-18 05:12:58', '2018-03-12', '10:00:00', '2018-03-15'),
 ('r15', 'h_92', 'c_2', '2018-04-19 11:25:00', '2018-05-04', '12:30:00', '2018-05-05'),
 ('r16', 'h_135', 'c_2', '2018-07-06 04:18:28', '2018-07-08', '10:00:00', '2018-07-09'),
 ('r17', 'h_115', 'c_3', '2016-05-10 12:20:32', '2016-05-17', '10:00:00', '2016-05-19'),
 ('r18', 'h_132', 'c_3', '2016-10-22 02:18:48', '2016-11-12', '12:00:00', '2016-11-13'),
 ('r19', 'h_23', 'c_3', '2017-01-11 22:54:09', '2017-02-08', '10:00:00', '2017-02-10'),
 ('r20', 'h_292', 'c_3', '2017-02-23 07:10:30', '2017-03-03', '11:00:00', '2017-03-04'),
 ('r21', 'h_153', 'c_3', '2017-04-06 18:12:10', '2017-04-16', '09:00:00', '2017-04-19'),
 ('r22', 'h_12', 'c_3', '2017-07-24 19:15:54', '2017-08-08', '09:00:00', '2017-08-09'),
 ('r23', 'h_61', 'c_3', '2017-12-16 23:31:04', '2018-01-09', '09:00:00', '2018-01-12'),
 ('r24', 'h_34', 'c_3', '2018-04-27 08:51:07', '2018-05-07', '09:30:00', '2018-05-10'),
 ('r25', 'h_277', 'c_4', '2016-03-28 07:17:34', '2016-04-07', '10:30:00', '2016-04-10'),
 ('r26', 'h_132', 'c_4', '2016-05-11 17:48:07', '2016-06-05', '11:30:00', '2016-06-06'),
 ('r27', 'h_97', 'c_4', '2016-07-08 14:10:06', '2016-07-16', '10:30:00', '2016-07-17'),
 ('r28', 'h_119', 'c_4', '2016-10-07 04:38:54', '2016-11-04', '10:00:00', '2016-11-06'),
 ('r29', 'h_222', 'c_4', '2016-11-10 21:59:02', '2016-11-13', '12:30:00', '2016-11-16'),
 ('r30', 'h_34', 'c_4', '2017-03-14 23:02:05', '2017-03-14', '11:30:00', '2017-03-17'),
 ('r31', 'h_143', 'c_4', '2017-08-17 03:16:51', '2017-09-14', '10:30:00', '2017-09-15'),
 ('r32', 'h_287', 'c_4', '2017-11-02 19:00:21', '2017-11-05', '10:00:00', '2017-11-07'),
 ('r33', 'h_82', 'c_5', '2016-05-19 18:50:58', '2016-05-30', '11:00:00', '2016-06-01'),
 ('r34', 'h_273', 'c_5', '2016-11-25 15:44:32', '2016-12-19', '12:00:00', '2016-12-22'),
 ('r35', 'h_90', 'c_5', '2017-03-30 13:38:03', '2017-04-05', '11:30:00', '2017-04-07'),
 ('r36', 'h_277', 'c_5', '2017-07-23 16:33:45', '2017-08-06', '12:30:00', '2017-08-08'),
 ('r37', 'h_226', 'c_6', '2016-06-14 11:14:05', '2016-06-28', '11:30:00', '2016-07-01'),
 ('r38', 'h_199', 'c_6', '2016-08-14 08:19:10', '2016-09-01', '12:30:00', '2016-09-02'),
 ('r39', 'h_232', 'c_7', '2016-03-21 16:14:52', '2016-04-10', '10:00:00', '2016-04-11'),
 ('r40', 'h_102', 'c_7', '2016-09-01 01:19:57', '2016-09-17', '11:30:00', '2016-09-18'),
 ('r41', 'h_23', 'c_7', '2016-10-14 02:41:13', '2016-10-15', '12:00:00', '2016-10-16'),
 ('r42', 'h_63', 'c_7', '2016-11-11 12:42:32', '2016-11-26', '09:00:00', '2016-11-29'),
 ('r43', 'h_224', 'c_7', '2017-04-22 20:03:46', '2017-05-22', '11:00:00', '2017-05-25'),
 ('r44', 'h_145', 'c_7', '2017-06-23 23:56:10', '2017-07-18', '09:30:00', '2017-07-21'),
 ('r45', 'h_104', 'c_7', '2017-09-28 11:44:02', '2017-10-05', '09:00:00', '2017-10-07'),
 ('r46', 'h_146', 'c_8', '2016-04-01 10:44:33', '2016-04-02', '09:30:00', '2016-04-05'),
 ('r47', 'h_56', 'c_8', '2016-06-15 07:00:28', '2016-07-02', '10:00:00', '2016-07-05'),
 ('r48', 'h_299', 'c_8', '2016-10-05 08:53:39', '2016-10-14', '09:30:00', '2016-10-16'),
 ('r49', 'h_183', 'c_8', '2017-01-25 00:25:04', '2017-02-14', '12:30:00', '2017-02-17'),
 ('r50', 'h_176', 'c_8', '2017-06-12 10:21:33', '2017-07-01', '11:00:00', '2017-07-02'),
 ('r51', 'h_207', 'c_8', '2017-11-05 01:53:19', '2017-11-19', '12:00:00', '2017-11-21'),
 ('r52', 'h_152', 'c_8', '2017-12-30 22:27:20', '2018-01-16', '11:00:00', '2018-01-18'),
 ('r53', 'h_149', 'c_8', '2018-05-08 10:44:17', '2018-05-12', '12:00:00', '2018-05-13'),
 ('r54', 'h_170', 'c_9', '2016-03-18 21:40:15', '2016-04-06', '12:00:00', '2016-04-08'),
 ('r55', 'h_55', 'c_9', '2016-07-05 05:39:25', '2016-07-21', '11:30:00', '2016-07-22'),
 ('r56', 'h_33', 'c_9', '2016-11-04 14:04:58', '2016-12-01', '12:30:00', '2016-12-03'),
 ('r57', 'h_25', 'c_9', '2016-12-11 22:04:58', '2016-12-20', '09:30:00', '2016-12-21'),
 ('r58', 'h_187', 'c_9', '2017-04-02 17:22:52', '2017-04-07', '11:30:00', '2017-04-10'),
 ('r59', 'h_245', 'c_10', '2016-06-20 11:10:52', '2016-07-08', '11:00:00', '2016-07-10'),
 ('r60', 'h_102', 'c_10', '2016-10-23 01:56:42', '2016-11-01', '11:00:00', '2016-11-03'),
 ('r61', 'h_62', 'c_10', '2017-03-12 00:45:50', '2017-04-08', '10:00:00', '2017-04-10'),
 ('r62', 'h_21', 'c_10', '2017-07-29 17:48:41', '2017-08-06', '12:00:00', '2017-08-08'),
 ('r63', 'h_142', 'c_10', '2017-09-11 19:41:28', '2017-09-13', '10:00:00', '2017-09-15'),
 ('r64', 'h_112', 'c_10', '2018-03-07 00:43:22', '2018-03-13', '12:30:00', '2018-03-14'),
 ('r65', 'h_221', 'c_11', '2016-01-24 18:58:29', '2016-02-19', '12:30:00', '2016-02-22'),
 ('r66', 'h_16', 'c_11', '2016-07-09 18:47:35', '2016-07-19', '11:00:00', '2016-07-22'),
 ('r67', 'h_142', 'c_11', '2016-12-04 20:14:40', '2016-12-16', '11:30:00', '2016-12-17'),
 ('r68', 'h_273', 'c_11', '2017-03-25 19:06:52', '2017-04-13', '09:30:00', '2017-04-15'),
 ('r69', 'h_37', 'c_11', '2017-06-21 13:43:11', '2017-07-03', '12:30:00', '2017-07-04'),
 ('r70', 'h_98', 'c_11', '2017-12-18 08:30:21', '2017-12-18', '11:00:00', '2017-12-19'),
 ('r71', 'h_183', 'c_11', '2018-04-14 19:30:43', '2018-04-19', '11:00:00', '2018-04-21'),
 ('r72', 'h_88', 'c_11', '2018-06-04 07:11:35', '2018-07-01', '11:00:00', '2018-07-04'),
 ('r73', 'h_15', 'c_12', '2016-06-27 14:53:03', '2016-07-26', '12:30:00', '2016-07-28'),
 ('r74', 'h_211', 'c_12', '2016-10-02 17:16:35', '2016-10-30', '09:30:00', '2016-10-31'),
 ('r75', 'h_66', 'c_12', '2017-02-12 01:36:07', '2017-02-17', '10:30:00', '2017-02-19'),
 ('r76', 'h_268', 'c_13', '2016-05-17 13:30:36', '2016-05-27', '12:00:00', '2016-05-30'),
 ('r77', 'h_228', 'c_13', '2016-10-29 06:30:43', '2016-11-09', '10:30:00', '2016-11-10'),
 ('r78', 'h_66', 'c_13', '2017-02-05 15:23:46', '2017-02-19', '12:30:00', '2017-02-21'),
 ('r79', 'h_218', 'c_13', '2017-03-02 05:54:51', '2017-03-19', '10:30:00', '2017-03-22'),
 ('r80', 'h_16', 'c_13', '2017-08-18 14:39:39', '2017-09-07', '11:30:00', '2017-09-10'),
 ('r81', 'h_205', 'c_13', '2018-02-28 04:15:24', '2018-02-28', '09:30:00', '2018-03-03'),
 ('r82', 'h_180', 'c_13', '2018-05-08 04:08:51', '2018-05-15', '09:00:00', '2018-05-18'),
 ('r83', 'h_98', 'c_15', '2016-02-29 22:51:44', '2016-03-10', '10:00:00', '2016-03-13'),
 ('r84', 'h_57', 'c_15', '2016-06-07 21:24:59', '2016-06-26', '12:30:00', '2016-06-29'),
 ('r85', 'h_245', 'c_15', '2016-08-11 07:51:14', '2016-08-18', '09:30:00', '2016-08-21'),
 ('r86', 'h_126', 'c_15', '2016-09-26 00:57:30', '2016-10-16', '11:30:00', '2016-10-17'),
 ('r87', 'h_52', 'c_15', '2017-02-01 05:59:40', '2017-02-21', '11:00:00', '2017-02-23'),
 ('r88', 'h_287', 'c_15', '2017-07-25 14:18:56', '2017-07-29', '10:00:00', '2017-08-01'),
 ('r89', 'h_252', 'c_15', '2017-09-03 23:04:30', '2017-09-08', '11:00:00', '2017-09-09'),
 ('r90', 'h_219', 'c_15', '2017-12-17 10:06:39', '2018-01-13', '09:00:00', '2018-01-14'),
 ('r91', 'h_232', 'c_16', '2016-04-23 22:14:26', '2016-05-11', '09:00:00', '2016-05-12'),
 ('r92', 'h_2', 'c_16', '2016-10-17 10:01:09', '2016-10-18', '11:30:00', '2016-10-20'),
 ('r93', 'h_19', 'c_16', '2017-03-04 13:13:38', '2017-03-22', '11:30:00', '2017-03-24'),
 ('r94', 'h_242', 'c_16', '2017-08-04 08:00:46', '2017-08-25', '12:00:00', '2017-08-26'),
 ('r95', 'h_186', 'c_16', '2017-11-17 09:57:42', '2017-11-29', '09:30:00', '2017-12-02'),
 ('r96', 'h_127', 'c_17', '2016-06-08 22:39:12', '2016-07-08', '10:00:00', '2016-07-09'),
 ('r97', 'h_133', 'c_17', '2016-12-04 05:26:50', '2016-12-14', '11:00:00', '2016-12-16'),
 ('r98', 'h_57', 'c_17', '2017-02-12 20:18:00', '2017-02-20', '10:00:00', '2017-02-22'),
 ('r99', 'h_262', 'c_17', '2017-06-02 12:53:09', '2017-06-03', '10:00:00', '2017-06-05'),
 ('r100', 'h_64', 'c_17', '2017-11-21 21:53:25', '2017-12-08', '12:30:00', '2017-12-09'),
 ('r101', 'h_168', 'c_17', '2018-04-19 02:43:02', '2018-05-12', '11:30:00', '2018-05-14'),
 ('r102', 'h_253', 'c_17', '2018-08-20 13:02:17', '2018-09-03', '09:30:00', '2018-09-04'),
 ('r103', 'h_118', 'c_18', '2016-05-24 10:42:22', '2016-05-31', '09:00:00', '2016-06-03'),
 ('r104', 'h_88', 'c_19', '2016-05-21 09:08:53', '2016-06-05', '09:30:00', '2016-06-07'),
 ('r105', 'h_233', 'c_21', '2016-02-28 09:18:25', '2016-03-24', '09:30:00', '2016-03-26'),
 ('r106', 'h_266', 'c_21', '2016-07-21 11:10:16', '2016-07-26', '10:30:00', '2016-07-28'),
 ('r107', 'h_257', 'c_21', '2016-12-11 09:38:58', '2016-12-29', '12:00:00', '2017-01-01'),
 ('r108', 'h_3', 'c_21', '2017-05-14 13:38:33', '2017-05-31', '11:30:00', '2017-06-02'),
 ('r109', 'h_167', 'c_21', '2017-06-05 19:12:54', '2017-06-14', '10:00:00', '2017-06-16'),
 ('r110', 'h_289', 'c_22', '2016-06-29 08:56:44', '2016-07-29', '09:30:00', '2016-08-01'),
 ('r111', 'h_146', 'c_22', '2016-12-31 06:14:03', '2017-01-16', '10:00:00', '2017-01-18'),
 ('r112', 'h_70', 'c_22', '2017-04-07 13:08:25', '2017-04-27', '09:30:00', '2017-04-28'),
 ('r113', 'h_13', 'c_22', '2017-09-16 02:42:03', '2017-10-09', '11:00:00', '2017-10-11'),
 ('r114', 'h_33', 'c_22', '2018-04-07 16:58:44', '2018-04-08', '11:30:00', '2018-04-11'),
 ('r115', 'h_88', 'c_22', '2018-08-24 12:36:44', '2018-09-11', '12:30:00', '2018-09-13'),
 ('r116', 'h_82', 'c_22', '2019-01-23 15:52:01', '2019-02-08', '12:30:00', '2019-02-09'),
 ('r117', 'h_221', 'c_22', '2019-02-25 03:10:39', '2019-03-13', '11:30:00', '2019-03-15'),
 ('r118', 'h_296', 'c_24', '2016-04-27 08:49:46', '2016-05-07', '12:00:00', '2016-05-09'),
 ('r119', 'h_300', 'c_24', '2016-09-13 17:46:44', '2016-09-13', '09:00:00', '2016-09-15'),
 ('r120', 'h_223', 'c_24', '2016-12-15 17:34:56', '2017-01-01', '09:00:00', '2017-01-03'),
 ('r121', 'h_216', 'c_24', '2017-02-05 18:19:39', '2017-03-04', '09:30:00', '2017-03-05'),
 ('r122', 'h_235', 'c_25', '2016-03-08 03:58:16', '2016-03-09', '09:30:00', '2016-03-11'),
 ('r123', 'h_69', 'c_25', '2016-05-02 22:17:12', '2016-05-02', '10:30:00', '2016-05-05'),
 ('r124', 'h_64', 'c_25', '2016-06-28 22:29:14', '2016-07-06', '12:30:00', '2016-07-07'),
 ('r125', 'h_23', 'c_26', '2016-01-29 18:51:24', '2016-02-18', '12:30:00', '2016-02-21'),
 ('r126', 'h_138', 'c_26', '2016-05-29 19:47:10', '2016-06-06', '10:30:00', '2016-06-07'),
 ('r127', 'h_138', 'c_26', '2016-09-10 06:22:03', '2016-09-13', '10:00:00', '2016-09-16'),
 ('r128', 'h_177', 'c_26', '2016-11-20 21:48:48', '2016-12-15', '09:00:00', '2016-12-18'),
 ('r129', 'h_255', 'c_26', '2017-06-09 16:37:12', '2017-07-01', '10:30:00', '2017-07-02'),
 ('r130', 'h_247', 'c_26', '2017-07-09 23:10:14', '2017-08-05', '11:30:00', '2017-08-06'),
 ('r131', 'h_269', 'c_26', '2017-12-17 09:21:43', '2018-01-06', '11:30:00', '2018-01-08'),
 ('r132', 'h_295', 'c_26', '2018-05-05 04:32:58', '2018-05-19', '11:00:00', '2018-05-20'),
 ('r133', 'h_242', 'c_27', '2016-06-15 04:53:54', '2016-07-07', '10:00:00', '2016-07-09'),
 ('r134', 'h_105', 'c_27', '2016-07-18 23:35:27', '2016-07-30', '09:30:00', '2016-07-31'),
 ('r135', 'h_91', 'c_27', '2016-12-16 10:42:36', '2017-01-04', '10:30:00', '2017-01-06'),
 ('r136', 'h_110', 'c_27', '2017-02-26 17:20:34', '2017-03-24', '10:00:00', '2017-03-25'),
 ('r137', 'h_37', 'c_27', '2017-07-28 11:33:00', '2017-08-01', '12:30:00', '2017-08-02'),
 ('r138', 'h_151', 'c_27', '2017-12-09 20:32:44', '2017-12-25', '11:30:00', '2017-12-26'),
 ('r139', 'h_143', 'c_27', '2018-04-27 08:16:46', '2018-05-27', '11:00:00', '2018-05-30'),
 ('r140', 'h_221', 'c_28', '2016-03-13 23:16:53', '2016-03-16', '09:30:00', '2016-03-18'),
 ('r141', 'h_156', 'c_28', '2016-05-28 07:18:18', '2016-06-08', '10:30:00', '2016-06-11'),
 ('r142', 'h_215', 'c_28', '2016-07-23 23:33:42', '2016-07-27', '09:30:00', '2016-07-29'),
 ('r143', 'h_222', 'c_29', '2016-03-11 20:22:07', '2016-03-30', '12:30:00', '2016-03-31'),
 ('r144', 'h_98', 'c_29', '2016-06-30 17:33:34', '2016-07-12', '10:00:00', '2016-07-15'),
 ('r145', 'h_206', 'c_29', '2016-12-05 19:27:14', '2016-12-26', '09:30:00', '2016-12-29'),
 ('r146', 'h_294', 'c_30', '2016-03-31 02:38:28', '2016-04-22', '09:30:00', '2016-04-23'),
 ('r147', 'h_175', 'c_31', '2016-01-16 11:31:19', '2016-02-14', '11:30:00', '2016-02-17'),
 ('r148', 'h_245', 'c_31', '2016-04-07 23:48:27', '2016-04-09', '11:30:00', '2016-04-12'),
 ('r149', 'h_81', 'c_31', '2016-08-25 05:32:05', '2016-09-01', '11:00:00', '2016-09-02'),
 ('r150', 'h_70', 'c_31', '2017-01-08 15:02:48', '2017-02-07', '11:30:00', '2017-02-10'),
 ('r151', 'h_133', 'c_31', '2017-06-11 21:05:11', '2017-07-10', '11:30:00', '2017-07-13'),
 ('r152', 'h_282', 'c_31', '2017-08-26 23:16:15', '2017-09-02', '11:30:00', '2017-09-04'),
 ('r153', 'h_165', 'c_31', '2018-02-05 08:13:38', '2018-02-13', '11:00:00', '2018-02-14'),
 ('r154', 'h_92', 'c_33', '2016-02-18 04:36:31', '2016-03-13', '12:30:00', '2016-03-16'),
 ('r155', 'h_70', 'c_33', '2016-06-16 02:43:13', '2016-07-15', '12:00:00', '2016-07-16'),
 ('r156', 'h_40', 'c_34', '2016-06-06 20:04:33', '2016-06-30', '12:30:00', '2016-07-01'),
 ('r157', 'h_198', 'c_34', '2016-09-10 15:17:45', '2016-09-17', '12:30:00', '2016-09-20'),
 ('r158', 'h_16', 'c_34', '2016-09-20 13:46:19', '2016-09-29', '12:00:00', '2016-09-30'),
 ('r159', 'h_92', 'c_34', '2016-12-30 02:10:30', '2017-01-04', '11:00:00', '2017-01-06'),
 ('r160', 'h_110', 'c_34', '2017-03-21 01:10:39', '2017-04-04', '11:00:00', '2017-04-05'),
 ('r161', 'h_105', 'c_34', '2017-07-27 00:59:25', '2017-08-12', '09:30:00', '2017-08-13'),
 ('r162', 'h_160', 'c_34', '2017-12-29 23:34:35', '2018-01-16', '11:00:00', '2018-01-17'),
 ('r163', 'h_70', 'c_36', '2016-06-29 10:35:22', '2016-07-19', '11:00:00', '2016-07-22'),
 ('r164', 'h_40', 'c_36', '2016-12-06 05:50:33', '2016-12-30', '10:30:00', '2017-01-01'),
 ('r165', 'h_224', 'c_36', '2017-03-16 07:19:06', '2017-04-13', '09:00:00', '2017-04-16'),
 ('r166', 'h_121', 'c_36', '2017-06-02 12:26:17', '2017-06-26', '09:00:00', '2017-06-29'),
 ('r167', 'h_78', 'c_36', '2017-11-30 07:10:04', '2017-12-11', '11:30:00', '2017-12-14'),
 ('r168', 'h_178', 'c_36', '2017-12-24 03:37:39', '2018-01-16', '09:30:00', '2018-01-18'),
 ('r169', 'h_239', 'c_36', '2018-06-17 17:22:09', '2018-06-30', '10:00:00', '2018-07-03'),
 ('r170', 'h_181', 'c_39', '2016-05-06 09:40:45', '2016-05-21', '11:30:00', '2016-05-24'),
 ('r171', 'h_251', 'c_39', '2016-07-06 15:56:31', '2016-07-10', '09:30:00', '2016-07-11'),
 ('r172', 'h_255', 'c_39', '2016-07-28 10:40:45', '2016-08-08', '09:30:00', '2016-08-09'),
 ('r173', 'h_240', 'c_39', '2016-10-01 11:21:45', '2016-10-09', '11:00:00', '2016-10-11'),
 ('r174', 'h_22', 'c_39', '2017-01-22 01:46:15', '2017-02-18', '10:00:00', '2017-02-21'),
 ('r175', 'h_204', 'c_40', '2016-06-03 06:57:50', '2016-06-27', '09:30:00', '2016-06-28'),
 ('r176', 'h_229', 'c_40', '2016-11-06 21:53:45', '2016-11-11', '12:00:00', '2016-11-12'),
 ('r177', 'h_236', 'c_41', '2016-06-13 05:01:58', '2016-07-04', '09:30:00', '2016-07-07'),
 ('r178', 'h_82', 'c_41', '2016-07-28 18:38:18', '2016-08-19', '11:30:00', '2016-08-21'),
 ('r179', 'h_153', 'c_41', '2017-01-02 05:32:31', '2017-01-22', '11:30:00', '2017-01-25'),
 ('r180', 'h_13', 'c_41', '2017-05-12 09:22:23', '2017-06-08', '12:30:00', '2017-06-09'),
 ('r181', 'h_110', 'c_41', '2017-10-28 16:22:31', '2017-11-11', '12:00:00', '2017-11-14'),
 ('r182', 'h_42', 'c_41', '2017-12-16 20:21:24', '2018-01-10', '09:00:00', '2018-01-13'),
 ('r183', 'h_69', 'c_41', '2018-04-15 20:33:37', '2018-04-30', '11:30:00', '2018-05-03'),
 ('r184', 'h_297', 'c_41', '2018-09-22 08:50:48', '2018-10-21', '12:30:00', '2018-10-24'),
 ('r185', 'h_75', 'c_43', '2016-03-23 06:27:35', '2016-04-07', '09:00:00', '2016-04-10'),
 ('r186', 'h_256', 'c_44', '2016-01-28 08:19:36', '2016-02-10', '12:00:00', '2016-02-13'),
 ('r187', 'h_107', 'c_44', '2016-06-12 14:19:17', '2016-06-28', '11:30:00', '2016-06-30'),
 ('r188', 'h_176', 'c_45', '2016-06-19 16:31:37', '2016-06-21', '10:00:00', '2016-06-24'),
 ('r189', 'h_284', 'c_45', '2016-10-03 07:25:08', '2016-10-18', '09:00:00', '2016-10-21'),
 ('r190', 'h_139', 'c_45', '2016-12-22 17:37:19', '2017-01-03', '11:00:00', '2017-01-06'),
 ('r191', 'h_239', 'c_45', '2017-03-11 07:34:10', '2017-04-09', '11:30:00', '2017-04-12'),
 ('r192', 'h_93', 'c_45', '2017-05-03 20:21:37', '2017-06-01', '11:30:00', '2017-06-02'),
 ('r193', 'h_4', 'c_45', '2017-07-19 15:13:50', '2017-07-31', '11:00:00', '2017-08-01'),
 ('r194', 'h_217', 'c_45', '2017-10-19 13:56:31', '2017-10-22', '09:30:00', '2017-10-25'),
 ('r195', 'h_148', 'c_45', '2018-03-04 11:06:01', '2018-03-04', '11:00:00', '2018-03-05'),
 ('r196', 'h_294', 'c_46', '2016-01-11 07:05:39', '2016-02-02', '10:00:00', '2016-02-05'),
 ('r197', 'h_38', 'c_46', '2016-03-18 06:25:54', '2016-04-13', '09:00:00', '2016-04-15'),
 ('r198', 'h_56', 'c_46', '2016-07-05 14:16:55', '2016-07-23', '12:30:00', '2016-07-24'),
 ('r199', 'h_285', 'c_46', '2016-12-05 06:32:23', '2016-12-14', '12:30:00', '2016-12-17'),
 ('r200', 'h_215', 'c_47', '2016-06-03 04:37:15', '2016-06-03', '11:00:00', '2016-06-05'),
 ('r201', 'h_24', 'c_47', '2016-11-22 21:12:12', '2016-12-03', '10:00:00', '2016-12-06'),
 ('r202', 'h_284', 'c_47', '2017-03-15 06:10:46', '2017-04-08', '12:00:00', '2017-04-10'),
 ('r203', 'h_127', 'c_47', '2017-09-24 00:33:57', '2017-10-07', '12:00:00', '2017-10-08'),
 ('r204', 'h_215', 'c_47', '2017-11-28 01:49:55', '2017-12-21', '10:00:00', '2017-12-24'),
 ('r205', 'h_31', 'c_47', '2018-02-19 07:46:23', '2018-02-22', '11:30:00', '2018-02-25'),
 ('r206', 'h_271', 'c_48', '2016-06-24 17:02:52', '2016-07-03', '09:30:00', '2016-07-04'),
 ('r207', 'h_274', 'c_48', '2016-11-04 02:19:49', '2016-11-04', '12:00:00', '2016-11-05'),
 ('r208', 'h_255', 'c_49', '2016-04-19 20:37:31', '2016-05-13', '12:30:00', '2016-05-14'),
 ('r209', 'h_32', 'c_49', '2016-05-21 03:54:23', '2016-06-10', '10:30:00', '2016-06-11'),
 ('r210', 'h_1', 'c_49', '2016-07-09 23:28:18', '2016-08-05', '12:00:00', '2016-08-08'),
 ('r211', 'h_277', 'c_49', '2016-11-26 15:13:16', '2016-11-29', '10:00:00', '2016-12-02'),
 ('r212', 'h_218', 'c_49', '2017-04-01 17:57:30', '2017-04-20', '11:30:00', '2017-04-21'),
 ('r213', 'h_275', 'c_49', '2017-05-15 12:57:10', '2017-05-16', '09:00:00', '2017-05-18'),
 ('r214', 'h_286', 'c_49', '2017-07-01 18:28:10', '2017-07-08', '12:00:00', '2017-07-10'),
 ('r215', 'h_291', 'c_49', '2017-10-14 18:59:28', '2017-11-09', '09:30:00', '2017-11-10'),
 ('r216', 'h_249', 'c_50', '2016-01-12 04:27:08', '2016-02-05', '10:00:00', '2016-02-06'),
 ('r217', 'h_114', 'c_50', '2016-02-18 12:27:18', '2016-03-10', '10:30:00', '2016-03-11'),
 ('r218', 'h_249', 'c_50', '2016-06-16 15:33:26', '2016-06-19', '12:00:00', '2016-06-20'),
 ('r219', 'h_275', 'c_50', '2016-08-05 05:42:33', '2016-08-12', '09:30:00', '2016-08-14'),
 ('r220', 'h_193', 'c_50', '2016-08-19 16:22:36', '2016-08-30', '12:00:00', '2016-08-31'),
 ('r221', 'h_231', 'c_51', '2016-02-08 14:40:50', '2016-02-19', '10:30:00', '2016-02-20'),
 ('r222', 'h_283', 'c_51', '2016-06-09 22:36:12', '2016-07-04', '10:00:00', '2016-07-05'),